"""empty message

Revision ID: 37182499d471
Revises: bc09e4785534
Create Date: 2019-12-09 11:11:35.582491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37182499d471'
down_revision = 'bc09e4785534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shows_artist_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_venue_id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'artist', ['artist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shows', 'venue', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_venue_id_fkey', 'shows', 'venue', ['venue_id'], ['id'])
    op.create_foreign_key('shows_artist_id_fkey', 'shows', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###
